# Generated by Django 4.0.3 on 2022-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a scoring model', max_length=30)),
                ('sql_text', models.TextField(help_text='SQL request for score', max_length=100000)),
            ],
        ),
    ]
